apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: podinfo-test
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/rakeshkrmeena/gitops-demo.git
    targetRevision: main
    path: envs/test
    helm:
      chart: podinfo
      repoURL: https://stefanprodan.github.io/podinfo
      targetRevision: 6.5.4
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: podinfo-test

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

